### ISSUE TITLE
Bug found on Automations page

### ISSUE THREAD

**Issue by charles-thompson-salesforce-com** [SalesforceLabs/OrgCheck#114] opened 2021-07-02 05:45 UTC
Hi, Vincent.  I encountered this error on my sandbox. 

Please go here and log an issue with the following information.

OrgCheck Information
Version: v1.9.4
Installed on OrgId: 00D5D000000Di2F

Navigation Information
Page: /apex/OrgCheck_Automations_VFP

System Information
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
Operating System: Win32
Language: en-NZ

Error #0: UNKNOWN_EXCEPTION
When: While creating a promise to call "private_query".
What:
index: 82
queryMore: undefined
queryString: SELECT Id, FullName, Metadata FROM WorkflowRule WHERE Id = '01Q6F000000FUu9UAG'
queryUseTooling: true
Stack:
UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 2122812588-19294 (-572470559)
   at h.getError (https://ANONYMIZED_MYDOMAIN.visualforce.com/resource/1625098800000/orgcheck__OrgCheck_JSForce_SR:3:9555)
   at https://ANONYMIZED_MYDOMAIN.visualforce.com/resource/1625098800000/orgcheck__OrgCheck_JSForce_SR:3:7905
   at o (https://ANONYMIZED_MYDOMAIN.visualforce.com/resource/1625098800000/orgcheck__OrgCheck_JSForce_SR:8:9228)
   at https://ANONYMIZED_MYDOMAIN.visualforce.com/resource/1625098800000/orgcheck__OrgCheck_JSForce_SR:8:10005
   at MutationObserver.r (https://ANONYMIZED_MYDOMAIN.visualforce.com/resource/1625098800000/orgcheck__OrgCheck_JSForce_SR:4:9798)

**Comment by VinceFINET** [comment] 2021-07-02 06:58
Duplicate of #73

**Closed as completed by VinceFINET** 2021-07-02 06:58 UTC
