### ISSUE TITLE
TAB object-information  REQUEST_LIMIT_EXCEEDED: ConcurrentRequests Limit exceeded.

### ISSUE THREAD

**Issue by githubuser12209** [SalesforceLabs/OrgCheck#432] opened 2024-08-07 08:21 UTC
**Issue Description** 

REQUEST_LIMIT_EXCEEDED: ConcurrentRequests (Concurrent API Requests) Limit exceeded.
    at r.getError (https://mysandbox--orgcheck.sandbox.vf.force.com/resource/1722601381000/orgcheck__OrgCheck_SR/js/jsforce.js:1:72641)
    at eval (https://mysandbox--orgcheck.sandbox.vf.force.com/resource/1722601381000/orgcheck__OrgCheck_SR/js/jsforce.js:1:71009)
    at eval (https://mysandbox--orgcheck.sandbox.vf.force.com/resource/1722601381000/orgcheck__OrgCheck_SR/js/jsforce.js:1:229493)
    at eval (https://mysandbox--orgcheck.sandbox.vf.force.com/resource/1722601381000/orgcheck__OrgCheck_SR/js/jsforce.js:1:229521)
    at o (https://mysandbox--orgcheck.sandbox.vf.force.com/resource/1722601381000/orgcheck__OrgCheck_SR/js/jsforce.js:1:104504)
    at MutationObserver.<anonymous> (https://static.lightning.force.com/cs339/auraFW/javascript/eGx3MHlRT1lEMUpQaWVxbGRUM1h0Z2hZX25NdHFVdGpDN3BnWlROY1ZGT3cyNTAuOC4zLTYuNC41/aura_prod.js:92:91749)
    at e.<computed> (https://static.lightning.force.com/cs339/auraFW/javascript/eGx3MHlRT1lEMUpQaWVxbGRUM1h0Z2hZX25NdHFVdGpDN3BnWlROY1ZGT3cyNTAuOC4zLTYuNC41/aura_prod.js:46:4694)

**Steps to replicate**
Once I select 'Standard Object' and Select Account and click **Apply**  the above error occurs

**Comment by githubuser12209** [comment] 2024-08-07 08:27
Just to update the org is 10Yrs + , we have lot of functionality so lot of components in the org. Not sure if this limit exceeded due to that reason

**Comment by VinceFINET** [comment] 2024-08-09 13:59
Thank you for logging this issue.
Do you have the same issue somewhere else on the app? like when hitting the custom fields tab?
Do you have the same issue with other objects?
Can you screenshot the progress dialogbox with the OrgCheck mascot moving, so i can see the steps you go throught...
THANK YOU!

**Comment by VinceFINET** [comment] 2024-08-09 14:02
Internal discussion --> Please check JSForce.Connection option parameter called "maxRequest"
see. https://jsforce.github.io/jsforce/doc/Connection.html

**Comment by VinceFINET** [comment] 2024-08-09 14:06
https://developer.salesforce.com/docs/atlas.en-us.234.0.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_apexgov.htm

**Comment by VinceFINET** [comment] 2024-08-09 14:08
by default the value is 10 for this option in JSForce
<img width="679" alt="image" src="https://github.com/user-attachments/assets/d2ba9078-ffb2-4ee5-b339-db02e8aecbea">

and in the code we set it to 20. 
may need to reconsider this override setting to solve this issue.

**Comment by VinceFINET** [comment] 2024-08-09 15:23
Please @githubuser12209 tell me if the upgrade changed something in your 10-year-old org (after a refresh of your cache/browser) Thank you !!

**Comment by githubuser12209** [comment] 2024-08-19 06:12
> Thank you for logging this issue. Do you have the same issue somewhere else on the app? like when hitting the custom fields tab? Do you have the same issue with other objects? Can you screenshot the progress dialogbox with the OrgCheck mascot moving, so i can see the steps you go throught... THANK YOU!

Hi @VinceFINET - Pls find the screenshot as requested - 
Step 1 (Initial screen after I select the Lead Object Only):
![image](https://github.com/user-attachments/assets/0ffed7d6-4b20-4290-a7bf-1c02fc660e6d)

Step 2: (In few mins, I get the below error )

![image](https://github.com/user-attachments/assets/9c80b360-39d6-459c-9b24-2e0c0d3cdcd9)


Even if I select Apex Class, Same issue is present for APEX classes as well - 

![image](https://github.com/user-attachments/assets/0e84dc94-d110-4aa2-b75b-8fb69c0f73b9)

**Comment by githubuser12209** [comment] 2024-08-19 06:15
> by default the value is 10 for this option in JSForce <img alt="image" width="679" src="https://private-user-images.githubusercontent.com/3799275/356627546-d2ba9078-ffb2-4ee5-b339-db02e8aecbea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNDc4MTUsIm5iZiI6MTcyNDA0NzUxNSwicGF0aCI6Ii8zNzk5Mjc1LzM1NjYyNzU0Ni1kMmJhOTA3OC1mZmIyLTRlZTUtYjMzOS1kYjAyZThhZWNiZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTlUMDYwNTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWJhMTEwNjdjN2QyODJlMjYzMjcxYTk1OGU4NmMxODExMWIxMmQ3ZjdlNWIwNThmYzI3NDU3MjRiYmEyOGI1NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EO_on7qbb25i9gLA2CmAQHNCwTEKng2ZYNCCqPD5aro">
> 
> and in the code we set it to 20. may need to reconsider this override setting to solve this issue.

@VinceFINET  Can you pls tell me where I can change this settings ? In installed the package but dont find any settings page to change the same , is it in some Apex Class , can you share the details ?

**Comment by githubuser12209** [comment] 2024-08-19 06:16
> Please @githubuser12209 tell me if the upgrade changed something in your 10-year-old org (after a refresh of your cache/browser) Thank you !!

@VinceFINET  @RubenHalman Sorry I was on holiday for some days, if you can get back to my quote queries , I will try that out and update accordingly

**Comment by masenk** [comment] 2024-08-21 21:12
I just upgraded to Beryllium 4.7 today and got the same error. I had everything selected, and I wanted to look at profiles and permissions but it didn't work. 

<img width="1340" alt="Screenshot 2024-08-21 at 5 04 35 PM" src="https://github.com/user-attachments/assets/f5845ef6-ce7d-4013-b539-ab1595952875">

**Comment by VinceFINET** [comment] 2024-09-10 11:41
> > by default the value is 10 for this option in JSForce <img alt="image" width="679" src="https://private-user-images.githubusercontent.com/3799275/356627546-d2ba9078-ffb2-4ee5-b339-db02e8aecbea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNDc4MTUsIm5iZiI6MTcyNDA0NzUxNSwicGF0aCI6Ii8zNzk5Mjc1LzM1NjYyNzU0Ni1kMmJhOTA3OC1mZmIyLTRlZTUtYjMzOS1kYjAyZThhZWNiZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTlUMDYwNTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWJhMTEwNjdjN2QyODJlMjYzMjcxYTk1OGU4NmMxODExMWIxMmQ3ZjdlNWIwNThmYzI3NDU3MjRiYmEyOGI1NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EO_on7qbb25i9gLA2CmAQHNCwTEKng2ZYNCCqPD5aro">
> > and in the code we set it to 20. may need to reconsider this override setting to solve this issue.
> 
> @VinceFINET Can you pls tell me where I can change this settings ? In installed the package but dont find any settings page to change the same , is it in some Apex Class , can you share the details ?

not a setting that you can change at the moment it's in the code and can't be changed by org check users...

**Comment by VinceFINET** [comment] 2024-09-10 11:44
not the same issue!
initially you had "REQUEST_LIMIT_EXCEEDED: ConcurrentRequests"
and now you have "INVALID_SESSIONID"

the later means are using org check with a token that expires.

can you close your borther, connect to your org then switch ot org check and tell us if this solved the issue.

Thank you

**Comment by VinceFINET** [comment] 2024-09-10 12:00
Update us when you have time. Thank you.

**Comment by VinceFINET** [comment] 2024-09-10 12:01
as this was also a bug in the code, please DM me your postal address so i can send you an Org Check sticker. or by email --> obviously not here please !!

**Comment by githubuser12209** [comment] 2024-09-11 16:53
> not the same issue! initially you had "REQUEST_LIMIT_EXCEEDED: ConcurrentRequests" and now you have "INVALID_SESSIONID"
> 
> the later means are using org check with a token that expires.
> 
> can you close your borther, connect to your org then switch ot org check and tell us if this solved the issue.
> 
> Thank you

Hi Vincent , my issue is still with the request time limit haven't faced the token expiration issue. The token expiration issue is for @masenk

**Comment by githubuser12209** [comment] 2024-09-11 16:53
@VinceFINET  This is the error I faced - [REQUEST_LIMIT_EXCEEDED: ConcurrentRequests Limit exceeded.](https://github.com/SalesforceLabs/OrgCheck/issues/432#top) , can you tell me if there is a way to resolve this ?

**Comment by githubuser12209** [comment] 2024-09-11 16:54
> as this was also a bug in the code, please DM me your postal address so i can send you an Org Check sticker. or by email --> obviously not here please !!

I did via email , thank you!

**Comment by VinceFINET** [comment] 2024-09-12 19:28
> I just upgraded to Beryllium 4.7 today and got the same error. I had everything selected, and I wanted to look at profiles and permissions but it didn't work.
> 
> <img alt="Screenshot 2024-08-21 at 5 04 35 PM" width="1340" src="https://private-user-images.githubusercontent.com/133985142/360106199-f5845ef6-ce7d-4013-b539-ab1595952875.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNjkzODQsIm5iZiI6MTcyNjE2OTA4NCwicGF0aCI6Ii8xMzM5ODUxNDIvMzYwMTA2MTk5LWY1ODQ1ZWY2LWNlN2QtNDAxMy1iNTM5LWFiMTU5NTk1Mjg3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQxOTI0NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTc3ZTYxMmMzZGQ1YzM5NjdhNzE3YTIxMDdlNzU0OWRkOGM1NDY2OWJkYTBkMjdjOWJjYzlkYzdiZTA5OWNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BxbqOMLtg_ytHCIrpecl2lHBMxMacus6crlnE05j2ZQ">

@masenk this error is documented here: https://salesforcelabs.github.io/OrgCheck/installation/
with a solution to it.
<img width="748" alt="image" src="https://github.com/user-attachments/assets/7a092448-dd48-4502-b690-d8fe85da1e47">

as this is not the same error as @githubuser12209 if you still have it, please create another issue. THANK YOU!

**Comment by VinceFINET** [comment] 2024-09-12 19:32
issue with the apex class tab is resolved via this ticket https://github.com/SalesforceLabs/OrgCheck/issues/433
(you have to wait for me to package it!)

**Comment by VinceFINET** [comment] 2024-09-12 19:51
about the DurableId issue you have on the Lead object.

- do you have the error only for Lead object?
- can you copy the entire stack trace here (including the end of each line, i need to know what's after ".js:1:"

Thank you @githubuser12209

**Comment by githubuser12209** [comment] 2024-09-18 14:56
@VinceFINET Not specific to Lead Object, this is happening for all objects even those objects which have very minimal fields and data as well. 

Here is the entire stack tree that I received - 

TypeError: Cannot read properties of null (reading 'DurableId')
    at eval (modules/orgcheck/orgcheckApp.js:3:133383)
    at eval (modules/orgcheck/orgcheckApp.js:3:90215)
    at Generator.next (<anonymous>)
    at Ds (modules/orgcheck/orgcheckApp.js:3:88668)
    at n (modules/orgcheck/orgcheckApp.js:3:88871)
    at eval (modules/orgcheck/orgcheckApp.js:3:88932)
    at eval (eval at <anonymous> (https://static.lightning.force.com/cs339/auraFW/javascript/eGx3MHlRT1lEMUpQaWVxbGRUM1h0Z2hZX25NdHFVdGpDN3BnWlROY1ZGT3cyNTAuOC40LTYuNC41/aura_prod.js:1:1), <anonymous>:3:23715)
    at en.<anonymous> (https://static.lightning.force.com/cs339/auraFW/javascript/eGx3MHlRT1lEMUpQaWVxbGRUM1h0Z2hZX25NdHFVdGpDN3BnWlROY1ZGT3cyNTAuOC40LTYuNC41/aura_prod.js:105:67030)
    at new Promise (<anonymous>)
    at https://static.lightning.force.com/cs339/auraFW/javascript/eGx3MHlRT1lEMUpQaWVxbGRUM1h0Z2hZX25NdHFVdGpDN3BnWlROY1ZGT3cyNTAuOC40LTYuNC41/aura_prod.js:105:85785

Screenshot - 

![image](https://github.com/user-attachments/assets/e511456a-3cef-40d6-a8d3-8b6041356164)

The entire highlighted RED part I have pasted above .

**Comment by VinceFINET** [comment] 2024-10-14 17:20
Can you try the following SOQL query from the **_tooling api_**:
```
SELECT Id, Name, ApiVersion, Status, NamespacePrefix, EntityDefinition.QualifiedApiName, 
      EntityDefinition.DurableId, CreatedDate, LastModifiedDate 
FROM ApexTrigger 
WHERE EntityDefinitionId = NULL
```

I believe in some case the `EntityDefinition` relationship is empty so if I add this `= NULL` statement that could solve the issue...

**Comment by githubuser12209** [comment] 2024-10-14 17:38
Hi ,

I got zero records while executing the above *SOQL Query*

[image: image.png]

And if I remove the where condition , I got around *582 records*

[image: image.png]

**Closed as completed** 2024-10-15 09:36 UTC
Labels: bug, really-a-bug

**Comment by githubuser12209** [comment] 2024-10-15 13:53
@VinceFINET shall i uninstall the old one and download the new one, where can i find the updated code link which i can install in my sandox

**Comment by VinceFINET** [comment] 2024-10-15 19:17
I will push the update tomorrow if it’s ok for you

Le mar. 15 oct. 2024 à 15:53, githubuser12209 ***@***.***> a
écrit :

**Comment by githubuser12209** [comment] 2024-10-16 02:17
Sure thank you very much

**Comment by VinceFINET** [comment] 2024-10-16 11:08
You can check your org by now!

**Comment by githubuser12209** [comment] 2024-10-22 15:49
thanks @VinceFINET , but on custom fields now I am getting Access Denied, shall I log a separate issue for that - 

ERROR_HTTP_400: Access Declined
    at r.getError (eval at <anonymous> (eval at <anonymous> (https://static.lightning.force.com/cs339/auraFW/javascript/ZzhjQmRxMXdrdzhvS0RJMG5qQVdxQTdEcXI0cnRHWU0zd2xrUnFaakQxNXc5LjMyMC4y/aura_prod.js:1:1)), <anonymous>:3:72751)
    at eval (eval at <anonymous> (eval at <anonymous> (https://static.lightning.force.com/cs339/auraFW/javascript/ZzhjQmRxMXdrdzhvS0RJMG5qQVdxQTdEcXI0cnRHWU0zd2xrUnFaakQxNXc5LjMyMC4y/aura_prod.js:1:1)), <anonymous>:3:71119)
    at eval (eval at <anonymous> (eval at <anonymous> (https://static.lightning.force.com/cs339/auraFW/javascript/ZzhjQmRxMXdrdzhvS0RJMG5qQVdxQTdEcXI0cnRHWU0zd2xrUnFaakQxNXc5LjMyMC4y/aura_prod.js:1:1)), <anonymous>:3:229610)
    at eval (eval at <anonymous> (eval at <anonymous> (https://static.lightning.force.com/cs339/auraFW/javascript/ZzhjQmRxMXdrdzhvS0RJMG5qQVdxQTdEcXI0cnRHWU0zd2xrUnFaakQxNXc5LjMyMC4y/aura_prod.js:1:1)), <anonymous>:3:229638)
    at Proxy.o (eval at <anonymous> (eval at <anonymous> (https://static.lightning.force.com/cs339/auraFW/javascript/ZzhjQmRxMXdrdzhvS0RJMG5qQVdxQTdEcXI0cnRHWU0zd2xrUnFaakQxNXc5LjMyMC4y/aura_prod.js:1:1)), <anonymous>:3:104621)
    at eval (eval at <anonymous> (https://static.lightning.force.com/cs339/auraFW/javascript/ZzhjQmRxMXdrdzhvS0RJMG5qQVdxQTdEcXI0cnRHWU0zd2xrUnFaakQxNXc5LjMyMC4y/aura_prod.js:1:1), <anonymous>:3:23715)
    at en.applyTrapForThreeOrMoreArgs (https://static.lightning.force.com/cs339/auraFW/javascript/ZzhjQmRxMXdrdzhvS0RJMG5qQVdxQTdEcXI0cnRHWU0zd2xrUnFaakQxNXc5LjMyMC4y/aura_prod.js:105:69972)
    at en.<anonymous> (https://static.lightning.force.com/cs339/auraFW/javascript/ZzhjQmRxMXdrdzhvS0RJMG5qQVdxQTdEcXI0cnRHWU0zd2xrUnFaakQxNXc5LjMyMC4y/aura_prod.js:105:68756)
    at e.<computed> (https://static.lightning.force.com/cs339/auraFW/javascript/ZzhjQmRxMXdrdzhvS0RJMG5qQVdxQTdEcXI0cnRHWU0zd2xrUnFaakQxNXc5LjMyMC4y/aura_prod.js:46:4529)

**Comment by VinceFINET** [comment] 2024-10-22 17:19
No need, this has been already reported to me and is logged as #436 
This issue is only happening in Chrome when the browser has no more resources to send requests to the Salesforce API.
I know how to handle it now as i know the root cause.
As a workaround you can use Safari or Firefox!

**Comment by githubuser12209** [comment] 2024-10-23 12:18
@VinceFINET same problem i am facing in firefox as well, I will track the logged issue , once you made the update i will check again, thanks !

![image](https://github.com/user-attachments/assets/648d99c2-aac3-43a0-ac92-9973592106dd)
