### ISSUE TITLE
Unable to open Automations tab

### ISSUE THREAD

**Issue by josegarciaponce** [SalesforceLabs/OrgCheck#152] opened 2022-01-28 17:01 UTC
**Describe the bug**
OrgCheck Information
Version: v1.9.6
Installed on OrgId: 00D190000001Fj9

Navigation Information
Page: /apex/OrgCheck_Automations_VFP

System Information
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
Operating System: MacIntel
Language: en-GB

Error #0: ERROR_HTTP_400
When: While creating a promise to call "private_query".
What:
index: 534
queryMore: undefined
queryString: SELECT Id, FullName, DefinitionId, MasterLabel, VersionNumber, Metadata, Status, Description, ProcessType FROM Flow WHERE Id = '30119000000C2HBAA0'
queryUseTooling: true
Stack:
ERROR_HTTP_400: Access Declined
   at h.getError (/resource/1643387700000/orgcheck__OrgCheck_JSForce_SR:3:9555)
   at /resource/1643387700000/orgcheck__OrgCheck_JSForce_SR:3:7905
   at o (/resource/1643387700000/orgcheck__OrgCheck_JSForce_SR:8:9228)
   at /resource/1643387700000/orgcheck__OrgCheck_JSForce_SR:8:10005
   at MutationObserver.r (/resource/1643387700000/orgcheck__OrgCheck_JSForce_SR:4:9798)
**To Reproduce**
Click on the Automations tab

**Comment by VinceFINET** [comment] 2022-01-29 11:56
Duplicate of #74

**Closed as completed by VinceFINET** 2022-01-29 11:57 UTC
Labels: bug
