### ISSUE TITLE
Error Running Automation analysis in partial sandbox

### ISSUE THREAD

**Issue by C0deShar1ng** [SalesforceLabs/OrgCheck#44] opened 2021-03-07 18:27 UTC
OrgCheck Information
Version: v1.9.1
Installed on OrgId: 00D010000004d48

Navigation Information
Page: /apex/OrgCheck_Automations_VFP

System Information
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36
Operating System: Win32
Language: en-US

Error #0: ERROR_HTTP_400
When: While creating a promise to call "private_query".
What:
index: 727
queryMore: undefined
queryString: SELECT Id, FullName, DefinitionId, MasterLabel, VersionNumber, Metadata, Status, Description, ProcessType FROM Flow WHERE Id = '301f3000000DOYNAA4'
queryUseTooling: true
ERROR_HTTP_400: Access Declined
   at h.getError (https://viventium--csstec--orgcheck.visualforce.com/resource/1615140835000/orgcheck__OrgCheck_JSForce_SR:3:6851)
   at https://viventium--csstec--orgcheck.visualforce.com/resource/1615140835000/orgcheck__OrgCheck_JSForce_SR:3:5201
   at o (https://viventium--csstec--orgcheck.visualforce.com/resource/1615140835000/orgcheck__OrgCheck_JSForce_SR:8:3810)
   at https://viventium--csstec--orgcheck.visualforce.com/resource/1615140835000/orgcheck__OrgCheck_JSForce_SR:8:4587
   at MutationObserver.r (https://viventium--csstec--orgcheck.visualforce.com/resource/1615140835000/orgcheck__OrgCheck_JSForce_SR:4:7059)

Error #1: TypeError
TypeError: Cannot read property 'm' of undefined
   at https://viventium--csstec--orgcheck.visualforce.com/resource/1615140835000/orgcheck__OrgCheck_OrgCheck_SR:1184:44

**Comment by VinceFINET** [comment] 2021-03-12 11:50
did you assign yourself to the PermissionSet of OrgCheck??

**Comment by C0deShar1ng** [comment] 2021-03-12 13:16
DOH! I had not. LOL!  I did just now, though, but still getting the error
on the Automation tab:


[image: image.png]
Randi Thompson
President
Imagine If, Inc.
Salesforce.com Consulting
215-990-3619

**Comment by VinceFINET** [comment] 2021-03-15 17:23
funny the error "ERROR_HTTP_400: Access Declined" is also the same in #45 
when closing the browser, cleaning the cache etc. do you reproduce the error??

**Comment by C0deShar1ng** [comment] 2021-03-19 12:19
Hi Vince!  Sorry for the delay. I cleared my cache and am still getting the
error.

[image: image.png]

Randi Thompson
President
Imagine If, Inc.
Salesforce.com Consulting
215-990-3619

**Comment by VinceFINET** [comment] 2021-03-19 17:21
Error is still the same.
The PB which causes the issue is readable from Workbench (with tooling API / rest explorer tool)
Deleting the PB that is causing the issue (see the id in the query) is letting you go a little bit further but unfortunately you had the same error but for another version of a different PB.
Thanks for your time.

I will continue to investigate.
Thank you for your time!

**Comment by VinceFINET** [comment] 2021-03-19 18:44
ERROR_HTTP_400: Access Declined --> also in #45

**Comment by VinceFINET** [comment] 2021-04-13 09:54
Duplicate of #74

**Closed as completed by VinceFINET** 2021-04-13 09:54 UTC
Labels: bug
