### ISSUE TITLE
Automations Error

### ISSUE THREAD

**Issue by energidi** [SalesforceLabs/OrgCheck#103] opened 2021-06-11 08:27 UTC
Hi,
After clicking on the 'Automation' tab, I received the following error:
OrgCheck Information
Version: v1.9.4
Installed on OrgId: 

Navigation Information
Page: /apex/OrgCheck_Automations_VFP

System Information
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36
Operating System: Win32
Language: he-IL

Error #0: ERROR_HTTP_400
When: While creating a promise to call "private_query".
What:
index: 1350
queryMore: undefined
queryString: SELECT Id, FullName, DefinitionId, MasterLabel, VersionNumber, Metadata, Status, Description, ProcessType FROM Flow WHERE Id = '3013W000000kBdCQAU'
queryUseTooling: true
Stack:
ERROR_HTTP_400: Access Declined
   at h.getError (https://ANONYMIZED_MYDOMAIN.visualforce.com/resource/1623397137000/orgcheck__OrgCheck_JSForce_SR:3:9555)
   at https://ANONYMIZED_MYDOMAIN.visualforce.com/resource/1623397137000/orgcheck__OrgCheck_JSForce_SR:3:7905
   at o (https://ANONYMIZED_MYDOMAIN.visualforce.com/resource/1623397137000/orgcheck__OrgCheck_JSForce_SR:8:9228)
   at https://ANONYMIZED_MYDOMAIN.visualforce.com/resource/1623397137000/orgcheck__OrgCheck_JSForce_SR:8:10005
   at MutationObserver.r (https://ANONYMIZED_MYDOMAIN.visualforce.com/resource/1623397137000/orgcheck__OrgCheck_JSForce_SR:4:9798)

**Comment by VinceFINET** [comment] 2021-06-11 08:38
Duplicate of #74

**Closed as completed** 2021-06-11 08:39 UTC
Labels: bug, duplicate
