### ISSUE TITLE
Org check in the loop not letting check anything

### ISSUE THREAD

**Issue by cbenitezSFDC** [SalesforceLabs/OrgCheck#470] opened 2024-11-28 16:23 UTC
**Describe the bug**
In the production org, the Org Check is spinning around without stopping.
**To Reproduce**
This is the error:
![image](https://github.com/user-attachments/assets/1dc86b8f-c1d2-4b70-ac87-782abf9d76f4)

**Comment by VinceFINET** [comment] 2024-11-28 16:44
Duplicate of #468

**Closed as completed by VinceFINET** 2024-11-28 16:44 UTC
Labels: bug

**Comment by VinceFINET** [comment] 2024-12-05 18:38
deployed !
