### ISSUE TITLE
Public Group tab - errors out (Oh no, OrgCheck had an error!)

### ISSUE THREAD

**Issue by sompublic** [SalesforceLabs/OrgCheck#33] opened 2021-02-16 20:39 UTC
When opening other tabs and then coming to check 'Public Group' tab in a sandbox org - getting the following error.
Tried multiple times with same result.

Error details:

Please go here and log an issue with the following information.

OrgCheck Information
Version: v1.8.3
Navigation Information
Page: /apex/OrgCheck_PublicGroups_VFP

System Information
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4420.0 Safari/537.36
Operating System: MacIntel
Language: en-US

Error #0: TypeError
TypeError: Cannot read property 'length' of undefined
   at renderGroups (https://acet-uhg--chspoc--orgcheck.visualforce.com/apex/OrgCheck_PublicGroups_VFP?sfdc.tabName=01r55000000M05k&vfRetURLInSFX=%2Fhome%2Fhome.jsp<n_app_id=06m55000000279nAAA&nonce=ce311e493b539dec966b31a3e35a72f427a149e9afa763cff95b811b84b33aed&sfdcIFrameOrigin=https://acet-uhg--chspoc.lightning.force.com&tour=&isdtp=p1&sfdcIFrameHost=web&clc=0:246:94)
   at Object.formula (https://acet-uhg--chspoc--orgcheck.visualforce.com/apex/OrgCheck_PublicGroups_VFP?sfdc.tabName=01r55000000M05k&vfRetURLInSFX=%2Fhome%2Fhome.jsp<n_app_id=06m55000000279nAAA&nonce=ce311e493b539dec966b31a3e35a72f427a149e9afa763cff95b811b84b33aed&sfdcIFrameOrigin=https://acet-uhg--chspoc.lightning.force.com&tour=&isdtp=p1&sfdcIFrameHost=web&clc=0:362:89)
   at https://acet-uhg--chspoc--orgcheck.visualforce.com/resource/1613271583000/orgcheck__OrgCheck_OrgCheck_SR:1381:53
   at Array.forEach ()
   at https://acet-uhg--chspoc--orgcheck.visualforce.com/resource/1613271583000/orgcheck__OrgCheck_OrgCheck_SR:1374:41
   at Array.forEach ()
   at Object.create (https://acet-uhg--chspoc--orgcheck.visualforce.com/resource/1613271583000/orgcheck__OrgCheck_OrgCheck_SR:1370:38)
   at Object.onRecords (https://acet-uhg--chspoc--orgcheck.visualforce.com/apex/OrgCheck_PublicGroups_VFP?sfdc.tabName=01r55000000M05k&vfRetURLInSFX=%2Fhome%2Fhome.jsp<n_app_id=06m55000000279nAAA&nonce=ce311e493b539dec966b31a3e35a72f427a149e9afa763cff95b811b84b33aed&sfdcIFrameOrigin=https://acet-uhg--chspoc.lightning.force.com&tour=&isdtp=p1&sfdcIFrameHost=web&clc=0:349:51)
   at onEnd (https://acet-uhg--chspoc--orgcheck.visualforce.com/resource/1613271583000/orgcheck__OrgCheck_OrgCheck_SR:1075:34)
   at https://acet-uhg--chspoc--orgcheck.visualforce.com/resource/1613271583000/orgcheck__OrgCheck_OrgCheck_SR:1140:33

**Comment by VinceFINET** [comment] 2021-02-16 23:24
Duplicate of #22

**Closed as completed by VinceFINET** 2021-02-16 23:24 UTC
