### ISSUE TITLE
Error on Automations Tab

### ISSUE THREAD

**Issue by pgonzaleznetwork** [SalesforceLabs/OrgCheck#65] opened 2021-04-01 17:43 UTC
```
OrgCheck Information
Version: v1.9.2
Installed on OrgId: 00D1g000000AVy4

Navigation Information
Page: /apex/OrgCheck_Automations_VFP

System Information
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
Operating System: MacIntel
Language: en-GB

Error #0: TypeError
Stack:
TypeError: Cannot read property 'forEach' of null
   at Object.onEachRecordFromAPICallback (https://ANONYMIZED_MYDOMAIN.visualforce.com/resource/1617297959000/orgcheck__OrgCheck_OrgCheck_SR:2292:62)
   at Object.onEach (https://ANONYMIZED_MYDOMAIN.visualforce.com/resource/1617297959000/orgcheck__OrgCheck_OrgCheck_SR:1764:46)
   at wrap (https://ANONYMIZED_MYDOMAIN.visualforce.com/resource/1617297959000/orgcheck__OrgCheck_OrgCheck_SR:215:61)
   at https://ANONYMIZED_MYDOMAIN.visualforce.com/resource/1617297959000/orgcheck__OrgCheck_OrgCheck_SR:234:68
   at Array.forEach ()
   at callback_api (https://ANONYMIZED_MYDOMAIN.visualforce.com/resource/1617297959000/orgcheck__OrgCheck_OrgCheck_SR:234:48)
   at s (https://ANONYMIZED_MYDOMAIN.visualforce.com/resource/1617297959000/orgcheck__OrgCheck_JSForce_SR:3:16007)
   at e.exports. (https://ANONYMIZED_MYDOMAIN.visualforce.com/resource/1617297959000/orgcheck__OrgCheck_JSForce_SR:3:16102)
   at Object.h (https://ANONYMIZED_MYDOMAIN.visualforce.com/resource/1617297959000/orgcheck__OrgCheck_JSForce_SR:5:30119)
   at a (https://ANONYMIZED_MYDOMAIN.visualforce.com/resource/1617297959000/orgcheck__OrgCheck_JSForce_SR:5:28850)
```

**Comment by VinceFINET** [comment] 2021-04-13 17:47
Duplicate of #52

**Closed as completed by VinceFINET** 2021-04-13 17:47 UTC
Labels: bug
