### ISSUE TITLE
HTTP 400 Error -  While creating a promise to call private_query

### ISSUE THREAD

**Issue by ghost** [SalesforceLabs/OrgCheck#189] opened 2022-08-03 05:54 UTC
OrgCheck Information
Version: v1.9.7
Installed on OrgId: 00D5P0000009E37
Current running UserId: 0054a0000019ZDXAA2

Navigation Information
Page: /apex/OrgCheck_Automations_VFP

System Information
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Operating System: Win32
Language: en-US

Error #0: ERROR_HTTP_400
When: While creating a promise to call "private_query".
What:
index: 1357
queryMore: undefined
queryString: SELECT Id, FullName, DefinitionId, MasterLabel, VersionNumber, Metadata, Status, Description, ProcessType FROM Flow WHERE Id = '3014a0000000rHRAAY'
queryUseTooling: true
Stack:
ERROR_HTTP_400: Access Declined
   at r.getError (/resource/1659500723000/orgcheck__OrgCheck_JSForce_SR:1:72641)
   at /resource/1659500723000/orgcheck__OrgCheck_JSForce_SR:1:71009
   at /resource/1659500723000/orgcheck__OrgCheck_JSForce_SR:1:229622
   at /resource/1659500723000/orgcheck__OrgCheck_JSForce_SR:1:229650
   at MutationObserver.o (/resource/1659500723000/orgcheck__OrgCheck_JSForce_SR:1:104504)

**Comment by VinceFINET** [comment] 2022-08-03 07:03
thank you for logging this issue.
This is a duplicate of #74
It has been resolved in Hydrogen version (the next to come soon)
I will let you know when i push the version in your org.

**Closed as completed by VinceFINET** 2022-08-03 07:03 UTC
Labels: bug, duplicate
