### ISSUE TITLE
Automations Tab Error

### ISSUE THREAD

**Issue by gurditta** [SalesforceLabs/OrgCheck#179] opened 2022-06-09 14:50 UTC
OrgCheck Information
Version: v1.9.7
Installed on OrgId: 00D300000000zOc
Current running UserId: 0053400000Ass1aAAB

Navigation Information
Page: /apex/OrgCheck_Automations_VFP

System Information
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36
Operating System: Win32
Language: en-US

Error #0: ERROR_HTTP_400
When: While creating a promise to call "private_query".
What:
index: 621
queryMore: undefined
queryString: SELECT Id, FullName, Metadata FROM WorkflowRule WHERE Id = '01Q34000000Rg3UEAS'
queryUseTooling: true
Stack:
ERROR_HTTP_400: Access Declined
   at r.getError (/resource/1644509737000/orgcheck__OrgCheck_JSForce_SR:1:72641)
   at /resource/1644509737000/orgcheck__OrgCheck_JSForce_SR:1:71009
   at /resource/1644509737000/orgcheck__OrgCheck_JSForce_SR:1:229622
   at /resource/1644509737000/orgcheck__OrgCheck_JSForce_SR:1:229650
   at MutationObserver.o (/resource/1644509737000/orgcheck__OrgCheck_JSForce_SR:1:104504)

**Comment by VinceFINET** [comment] 2022-06-09 15:08
Duplicate of #74

**Closed as completed by VinceFINET** 2022-06-09 15:08 UTC
Labels: bug, duplicate
